travis:
  secure:
    BINSTAR_TOKEN: tWLXwvjP7DpKNdFFud3tMUmPSEcwbjbQDoO5RxOY1YUAqWd0fbAESwjTVNSb3qVof7byqpFo1EQaxAWzliHumEkQSdodlKx2fs5xHNUb4wVx2Tp8w0EycA0HEt3NgOZfFRLUfVS5w6HIRgTQoQ7U9ks9DrYw06o+zlXgKfqJnoB+bwvBxYdmnjfNnFEpuhOkIDUnZ+NWX0fkd/icG504MYrjEtMgmyLrdVNnhEm9yId/NUph1zxb+pg+lzDm8+vfG61GbW94UTKVCD8i8LAuh+ZYXpZOvyPipDlaSxbLomicMHRU31PTX+IJTQKLuC1NqXwvrXrRjUUxhYv3nFm1wiNRfoBB1JB10wQyEC1RrkMvCg+WQ3iKqDRQGfDVH+/uuO0o/8CJq996SQmAAaH2I9teqiUV1w0J5+F6ltjLVI7ueg7vYM6QCdHhZFggYdhHg5J0IxShiwMOIHiw+cFY2QRlk4isG22pbhzv0O7o9uIdrXBA0PibkXyCHa8aEhCoAWjqiX2Y2HpV9CUSV/EMsCPV9nUDfZ6n+9zqN47onaNnHJJEPsLFBNv9imgn6pk8LFu4DxDsCrZIWETp0+wmNcB2V1oVhxS/cM+5uaxuP3wp3ahxIsBy0kJNxyyNA01sHIJgnOBNb88WHrWabBL+vWIyRdmyIu7mIpYCWqfVQBg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
